### ISSUE TITLE
No ATSAMD21 Support

### ISSUE THREAD

**Issue by cupofRiesL** [XarkLabs/PDQ_GFX_Libs#14]
If you try to compile a Sketch for ATSAMD21 Boards like Arduino Zero or Feather M0 it will Exit with an Error like:

In file included from /home/USER/Arduino/Game/v1/base_w_pdq/base_w_pdq.ino:38:0:
/home/USER/Arduino/libraries/PDQ_ST7735/PDQ_ST7735.h:65:2: error: #error Oops! Currently hardware SPI is required. Bother Xark if you would like USI or bit-bang SPI supported.
 #error Oops!  Currently hardware SPI is required.  Bother Xark if you would like USI or bit-bang SPI supported.

I am not able to implement this but i think there is a way:

https://github.com/FastLED/FastLED/tree/master/platforms/arm/d21

**Comment by XarkLabs** [comment]
PDQ_GFX is mainly focused on AVR parts, so I think this is out of scope for the project.  Many of the optimizations aren't as important on faster 32-bit CPUs.  That said, if the low-level SPI communication was implemented the library can work on other architectures.
