### ISSUE TITLE
ILI9325c

### ISSUE THREAD

**Issue by phhoef** [XarkLabs/PDQ_GFX_Libs#15]
Hi,

I am using an Arduino Mega compatible board with the following LCD.
http://en.startek-lcd.com/IPS024/2015-11-21/22228.chtml
The LCD is driven by a ILI9325C controller.

Unfortunately, I am not able to change the MCU nor the display.
Any chance to support this controller?

**Comment by XarkLabs** [comment]
Hello.  I'm sorry, but it is not likely (anytime soon).  Doesn't look super hard, but I don't have this display.
