### ISSUE TITLE
Any plans on supporting the ESP8266?

### ISSUE THREAD

**Issue by smvg** [XarkLabs/PDQ_GFX_Libs#16]
Thanks for providing the community with such a good library (have used your library in other hardware several times)!

**Comment by XarkLabs** [comment]
Thanks for the complement!  I am not sure my library is really needed on esp8266 as it is a pretty fast chip (vs other existing libraries).  However,  I suspect it would be easy to replace the low-level SPI routines for 8266 and the rest is quite portable.
