### ISSUE TITLE
Esp32, worth or just pain?

### ISSUE THREAD

**Issue by ismenc** [XarkLabs/PDQ_GFX_Libs#28]
Hi.
I'm working with esp32 and ST7735, pretty disappointed with adafruit gfx (and spi display) performance I ended up in this repository.

As I see currently only avr architectures are supported. 
I've 2 questions.
Can the improvements in this library be ported to ESP32 stack? (how much effort will it require to me to do so?)
Also, as i cannot test it at the moment, do you think it will help with my projject problem which is shown in the next gif

![animation](https://user-images.githubusercontent.com/12835964/153578672-e1d1f726-6ae8-40b0-9042-7dd0ce1bab21.gif)

As you can see i'm displaying bitmap animations. The second one runs smoothly because every animation frame only adds more pixels and therefor it is not needed to 'clear' the previous frame. For the first animation i have to draw a black rectangle in order to clear the previous animation frame and it makes the time between frames bigger and flicker. As i cannot test right now i don't know if adapting and using the library will help my animations/printings to be smoother.

Thank you.

**Comment by XarkLabs** [comment]
The main optimizations were designed with AVR in mind, so probably better options.
