### ISSUE TITLE
RP2040 Support?

### ISSUE THREAD

**Issue by IAmOrion** [XarkLabs/PDQ_GFX_Libs#29]
Any chance this library will be updated to support the RP2040?

**Comment by XarkLabs** [comment]
Hello,

Thanks for the question, however I don’t think that makes sense, as it is specifically optimized for the AVR.  Also, RP2040 is powerful enough the main Adafruit library will probably run okay.  In fact, it appears it has already been optimized for RP2040.  See https://arduino-pico.readthedocs.io/en/latest/libraries.html <https://arduino-pico.readthedocs.io/en/latest/libraries.html>

Take it easy,
Xark
