### ISSUE TITLE
didnt get it to run with esp8266 nodemcu1.0

### ISSUE THREAD

**Issue by kobraevents** [XarkLabs/PDQ_GFX_Libs#30]
stock lib is to slow to draw gif files (draw every frame).

i replaced the folder of the zip with the original folder and renamed it. i placed the adafruit original  .h and .cpp files in the folder.
ive done this for gfx and st7735.

Compiler says "cant compile for board esp8266 nodemcu1" 

when i now replace all files in the folder with the original adafruit files it runs (slow).

sketch:
#include <SPI.h>
#include <SdFat.h>                // SD card & FAT filesystem library
#include <Adafruit_SPIFlash.h>    // SPI / QSPI flash library
#include <Adafruit_ImageReader.h> // Image-reading functions

#include "PDQ_GFX.h"        // PDQ: Core graphics library
#include "PDQ_ST7735_config.h"      // PDQ: ST7735 pins and other setup for this sketch
#include <PDQ_ST7735.h>     // PDQ: Hardware-specific driver library
PDQ_ST7735 tft;
Adafruit_Image       img;        // An image loaded into RAM
int32_t              width  = 0, // BMP image dimensions
                     height = 0;
SdFat                SD1;         // SD card filesystem
Adafruit_ImageReader reader(SD1); // Image-reader object, pass in SD filesys
void setup(void) {
  tft.initR(INITR_BLACKTAB);      // Init ST7735S chip, black tab
  tft.setRotation(1); delay(10);
SD1.begin(SD_CS, SD_SCK_MHZ(10));
}

void loop() {
}

**Comment by XarkLabs** [comment]
It is only designed for AVR CPUs.
